<?php
/**
 * FriendshipApi
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 * Generated by: https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/NexconnAI-Dev/nexconn-server-sdk-php).
 * https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Do not edit the class manually.
 */

namespace NexConnServerSdkPhp\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use NexConnServerSdkPhp\ApiException;
use NexConnServerSdkPhp\Configuration;
use NexConnServerSdkPhp\FormDataProcessor;
use NexConnServerSdkPhp\HeaderSelector;
use NexConnServerSdkPhp\ObjectSerializer;

/**
 * FriendshipApi Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */
class FriendshipApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'addFriend' => [
            'application/json',
        ],
        'getFriendPermission' => [
            'application/json',
        ],
        'getFriendRelationships' => [
            'application/json',
        ],
        'listFriends' => [
            'application/json',
        ],
        'removeAllFriends' => [
            'application/json',
        ],
        'removeFriends' => [
            'application/json',
        ],
        'setFriendPermission' => [
            'application/json',
        ],
        'setFriendProfile' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addFriend
     *
     * Add friend
     *

     * @param  \NexConnServerSdkPhp\Model\FriendAddRequest $friend_add_request friend_add_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addFriend'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\CodeOnlyResponse
     */
    public function addFriend($friend_add_request, string $contentType = self::contentTypes['addFriend'][0])
    {
        list($response) = $this->addFriendWithHttpInfo($friend_add_request, $contentType);
        return $response;
    }

    /**
     * Operation addFriendWithHttpInfo
     *
     * Add friend
     *

     * @param  \NexConnServerSdkPhp\Model\FriendAddRequest $friend_add_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addFriend'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\CodeOnlyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function addFriendWithHttpInfo($friend_add_request, string $contentType = self::contentTypes['addFriend'][0])
    {
        $request = $this->addFriendRequest($friend_add_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation addFriendAsync
     *
     * Add friend
     *

     * @param  \NexConnServerSdkPhp\Model\FriendAddRequest $friend_add_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addFriend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addFriendAsync($friend_add_request, string $contentType = self::contentTypes['addFriend'][0])
    {
        return $this->addFriendAsyncWithHttpInfo($friend_add_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addFriendAsyncWithHttpInfo
     *
     * Add friend
     *

     * @param  \NexConnServerSdkPhp\Model\FriendAddRequest $friend_add_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addFriend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addFriendAsyncWithHttpInfo($friend_add_request, string $contentType = self::contentTypes['addFriend'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\CodeOnlyResponse';
        $request = $this->addFriendRequest($friend_add_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'addFriend'
     *

     * @param  \NexConnServerSdkPhp\Model\FriendAddRequest $friend_add_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addFriend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function addFriendRequest($friend_add_request, string $contentType = self::contentTypes['addFriend'][0])
    {

        // verify the required parameter 'friend_add_request' is set
        if ($friend_add_request === null || (is_array($friend_add_request) && count($friend_add_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $friend_add_request when calling addFriend'
            );
        }


        $resourcePath = '/v4/friend/add';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($friend_add_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($friend_add_request));
            } else {
                $httpBody = $friend_add_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getFriendPermission
     *
     * Get friend permission
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionGetRequest $friend_permission_get_request friend_permission_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendPermission'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\FriendPermissionGetResponse
     */
    public function getFriendPermission($friend_permission_get_request, string $contentType = self::contentTypes['getFriendPermission'][0])
    {
        list($response) = $this->getFriendPermissionWithHttpInfo($friend_permission_get_request, $contentType);
        return $response;
    }

    /**
     * Operation getFriendPermissionWithHttpInfo
     *
     * Get friend permission
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionGetRequest $friend_permission_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendPermission'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\FriendPermissionGetResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFriendPermissionWithHttpInfo($friend_permission_get_request, string $contentType = self::contentTypes['getFriendPermission'][0])
    {
        $request = $this->getFriendPermissionRequest($friend_permission_get_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\FriendPermissionGetResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\FriendPermissionGetResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\FriendPermissionGetResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getFriendPermissionAsync
     *
     * Get friend permission
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionGetRequest $friend_permission_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendPermission'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFriendPermissionAsync($friend_permission_get_request, string $contentType = self::contentTypes['getFriendPermission'][0])
    {
        return $this->getFriendPermissionAsyncWithHttpInfo($friend_permission_get_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFriendPermissionAsyncWithHttpInfo
     *
     * Get friend permission
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionGetRequest $friend_permission_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendPermission'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFriendPermissionAsyncWithHttpInfo($friend_permission_get_request, string $contentType = self::contentTypes['getFriendPermission'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\FriendPermissionGetResponse';
        $request = $this->getFriendPermissionRequest($friend_permission_get_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFriendPermission'
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionGetRequest $friend_permission_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendPermission'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFriendPermissionRequest($friend_permission_get_request, string $contentType = self::contentTypes['getFriendPermission'][0])
    {

        // verify the required parameter 'friend_permission_get_request' is set
        if ($friend_permission_get_request === null || (is_array($friend_permission_get_request) && count($friend_permission_get_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $friend_permission_get_request when calling getFriendPermission'
            );
        }


        $resourcePath = '/v4/friend/permission/get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($friend_permission_get_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($friend_permission_get_request));
            } else {
                $httpBody = $friend_permission_get_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getFriendRelationships
     *
     * Get friend relationships
     *

     * @param  \NexConnServerSdkPhp\Model\FriendRelationshipGetRequest $friend_relationship_get_request friend_relationship_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendRelationships'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\FriendRelationshipGetResponse
     */
    public function getFriendRelationships($friend_relationship_get_request, string $contentType = self::contentTypes['getFriendRelationships'][0])
    {
        list($response) = $this->getFriendRelationshipsWithHttpInfo($friend_relationship_get_request, $contentType);
        return $response;
    }

    /**
     * Operation getFriendRelationshipsWithHttpInfo
     *
     * Get friend relationships
     *

     * @param  \NexConnServerSdkPhp\Model\FriendRelationshipGetRequest $friend_relationship_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendRelationships'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\FriendRelationshipGetResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFriendRelationshipsWithHttpInfo($friend_relationship_get_request, string $contentType = self::contentTypes['getFriendRelationships'][0])
    {
        $request = $this->getFriendRelationshipsRequest($friend_relationship_get_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\FriendRelationshipGetResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\FriendRelationshipGetResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\FriendRelationshipGetResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getFriendRelationshipsAsync
     *
     * Get friend relationships
     *

     * @param  \NexConnServerSdkPhp\Model\FriendRelationshipGetRequest $friend_relationship_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendRelationships'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFriendRelationshipsAsync($friend_relationship_get_request, string $contentType = self::contentTypes['getFriendRelationships'][0])
    {
        return $this->getFriendRelationshipsAsyncWithHttpInfo($friend_relationship_get_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFriendRelationshipsAsyncWithHttpInfo
     *
     * Get friend relationships
     *

     * @param  \NexConnServerSdkPhp\Model\FriendRelationshipGetRequest $friend_relationship_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendRelationships'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFriendRelationshipsAsyncWithHttpInfo($friend_relationship_get_request, string $contentType = self::contentTypes['getFriendRelationships'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\FriendRelationshipGetResponse';
        $request = $this->getFriendRelationshipsRequest($friend_relationship_get_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFriendRelationships'
     *

     * @param  \NexConnServerSdkPhp\Model\FriendRelationshipGetRequest $friend_relationship_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFriendRelationships'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFriendRelationshipsRequest($friend_relationship_get_request, string $contentType = self::contentTypes['getFriendRelationships'][0])
    {

        // verify the required parameter 'friend_relationship_get_request' is set
        if ($friend_relationship_get_request === null || (is_array($friend_relationship_get_request) && count($friend_relationship_get_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $friend_relationship_get_request when calling getFriendRelationships'
            );
        }


        $resourcePath = '/v4/friend/relationship/get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($friend_relationship_get_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($friend_relationship_get_request));
            } else {
                $httpBody = $friend_relationship_get_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listFriends
     *
     * List friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendListRequest $friend_list_request friend_list_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFriends'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\FriendListResponse
     */
    public function listFriends($friend_list_request, string $contentType = self::contentTypes['listFriends'][0])
    {
        list($response) = $this->listFriendsWithHttpInfo($friend_list_request, $contentType);
        return $response;
    }

    /**
     * Operation listFriendsWithHttpInfo
     *
     * List friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendListRequest $friend_list_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFriends'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\FriendListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listFriendsWithHttpInfo($friend_list_request, string $contentType = self::contentTypes['listFriends'][0])
    {
        $request = $this->listFriendsRequest($friend_list_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\FriendListResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\FriendListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\FriendListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listFriendsAsync
     *
     * List friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendListRequest $friend_list_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listFriendsAsync($friend_list_request, string $contentType = self::contentTypes['listFriends'][0])
    {
        return $this->listFriendsAsyncWithHttpInfo($friend_list_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listFriendsAsyncWithHttpInfo
     *
     * List friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendListRequest $friend_list_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listFriendsAsyncWithHttpInfo($friend_list_request, string $contentType = self::contentTypes['listFriends'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\FriendListResponse';
        $request = $this->listFriendsRequest($friend_list_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'listFriends'
     *

     * @param  \NexConnServerSdkPhp\Model\FriendListRequest $friend_list_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listFriendsRequest($friend_list_request, string $contentType = self::contentTypes['listFriends'][0])
    {

        // verify the required parameter 'friend_list_request' is set
        if ($friend_list_request === null || (is_array($friend_list_request) && count($friend_list_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $friend_list_request when calling listFriends'
            );
        }


        $resourcePath = '/v4/friend/list';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($friend_list_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($friend_list_request));
            } else {
                $httpBody = $friend_list_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation removeAllFriends
     *
     * Clean all friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendCleanRequest $friend_clean_request friend_clean_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeAllFriends'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\CodeOnlyResponse
     */
    public function removeAllFriends($friend_clean_request, string $contentType = self::contentTypes['removeAllFriends'][0])
    {
        list($response) = $this->removeAllFriendsWithHttpInfo($friend_clean_request, $contentType);
        return $response;
    }

    /**
     * Operation removeAllFriendsWithHttpInfo
     *
     * Clean all friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendCleanRequest $friend_clean_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeAllFriends'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\CodeOnlyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function removeAllFriendsWithHttpInfo($friend_clean_request, string $contentType = self::contentTypes['removeAllFriends'][0])
    {
        $request = $this->removeAllFriendsRequest($friend_clean_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation removeAllFriendsAsync
     *
     * Clean all friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendCleanRequest $friend_clean_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeAllFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeAllFriendsAsync($friend_clean_request, string $contentType = self::contentTypes['removeAllFriends'][0])
    {
        return $this->removeAllFriendsAsyncWithHttpInfo($friend_clean_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation removeAllFriendsAsyncWithHttpInfo
     *
     * Clean all friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendCleanRequest $friend_clean_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeAllFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeAllFriendsAsyncWithHttpInfo($friend_clean_request, string $contentType = self::contentTypes['removeAllFriends'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\CodeOnlyResponse';
        $request = $this->removeAllFriendsRequest($friend_clean_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'removeAllFriends'
     *

     * @param  \NexConnServerSdkPhp\Model\FriendCleanRequest $friend_clean_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeAllFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function removeAllFriendsRequest($friend_clean_request, string $contentType = self::contentTypes['removeAllFriends'][0])
    {

        // verify the required parameter 'friend_clean_request' is set
        if ($friend_clean_request === null || (is_array($friend_clean_request) && count($friend_clean_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $friend_clean_request when calling removeAllFriends'
            );
        }


        $resourcePath = '/v4/friend/remove-all';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($friend_clean_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($friend_clean_request));
            } else {
                $httpBody = $friend_clean_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation removeFriends
     *
     * Delete friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendDeleteRequest $friend_delete_request friend_delete_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeFriends'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\CodeOnlyResponse
     */
    public function removeFriends($friend_delete_request, string $contentType = self::contentTypes['removeFriends'][0])
    {
        list($response) = $this->removeFriendsWithHttpInfo($friend_delete_request, $contentType);
        return $response;
    }

    /**
     * Operation removeFriendsWithHttpInfo
     *
     * Delete friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendDeleteRequest $friend_delete_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeFriends'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\CodeOnlyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function removeFriendsWithHttpInfo($friend_delete_request, string $contentType = self::contentTypes['removeFriends'][0])
    {
        $request = $this->removeFriendsRequest($friend_delete_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation removeFriendsAsync
     *
     * Delete friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendDeleteRequest $friend_delete_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeFriendsAsync($friend_delete_request, string $contentType = self::contentTypes['removeFriends'][0])
    {
        return $this->removeFriendsAsyncWithHttpInfo($friend_delete_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation removeFriendsAsyncWithHttpInfo
     *
     * Delete friends
     *

     * @param  \NexConnServerSdkPhp\Model\FriendDeleteRequest $friend_delete_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function removeFriendsAsyncWithHttpInfo($friend_delete_request, string $contentType = self::contentTypes['removeFriends'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\CodeOnlyResponse';
        $request = $this->removeFriendsRequest($friend_delete_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'removeFriends'
     *

     * @param  \NexConnServerSdkPhp\Model\FriendDeleteRequest $friend_delete_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['removeFriends'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function removeFriendsRequest($friend_delete_request, string $contentType = self::contentTypes['removeFriends'][0])
    {

        // verify the required parameter 'friend_delete_request' is set
        if ($friend_delete_request === null || (is_array($friend_delete_request) && count($friend_delete_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $friend_delete_request when calling removeFriends'
            );
        }


        $resourcePath = '/v4/friend/remove';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($friend_delete_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($friend_delete_request));
            } else {
                $httpBody = $friend_delete_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation setFriendPermission
     *
     * Set friend permission
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionSetRequest $friend_permission_set_request friend_permission_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendPermission'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\CodeOnlyResponse
     */
    public function setFriendPermission($friend_permission_set_request, string $contentType = self::contentTypes['setFriendPermission'][0])
    {
        list($response) = $this->setFriendPermissionWithHttpInfo($friend_permission_set_request, $contentType);
        return $response;
    }

    /**
     * Operation setFriendPermissionWithHttpInfo
     *
     * Set friend permission
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionSetRequest $friend_permission_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendPermission'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\CodeOnlyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function setFriendPermissionWithHttpInfo($friend_permission_set_request, string $contentType = self::contentTypes['setFriendPermission'][0])
    {
        $request = $this->setFriendPermissionRequest($friend_permission_set_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation setFriendPermissionAsync
     *
     * Set friend permission
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionSetRequest $friend_permission_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendPermission'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setFriendPermissionAsync($friend_permission_set_request, string $contentType = self::contentTypes['setFriendPermission'][0])
    {
        return $this->setFriendPermissionAsyncWithHttpInfo($friend_permission_set_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation setFriendPermissionAsyncWithHttpInfo
     *
     * Set friend permission
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionSetRequest $friend_permission_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendPermission'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setFriendPermissionAsyncWithHttpInfo($friend_permission_set_request, string $contentType = self::contentTypes['setFriendPermission'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\CodeOnlyResponse';
        $request = $this->setFriendPermissionRequest($friend_permission_set_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'setFriendPermission'
     *

     * @param  \NexConnServerSdkPhp\Model\FriendPermissionSetRequest $friend_permission_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendPermission'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function setFriendPermissionRequest($friend_permission_set_request, string $contentType = self::contentTypes['setFriendPermission'][0])
    {

        // verify the required parameter 'friend_permission_set_request' is set
        if ($friend_permission_set_request === null || (is_array($friend_permission_set_request) && count($friend_permission_set_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $friend_permission_set_request when calling setFriendPermission'
            );
        }


        $resourcePath = '/v4/friend/permission/set';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($friend_permission_set_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($friend_permission_set_request));
            } else {
                $httpBody = $friend_permission_set_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation setFriendProfile
     *
     * Set friend profile
     *

     * @param  \NexConnServerSdkPhp\Model\FriendProfileSetRequest $friend_profile_set_request friend_profile_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendProfile'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\CodeOnlyResponse
     */
    public function setFriendProfile($friend_profile_set_request, string $contentType = self::contentTypes['setFriendProfile'][0])
    {
        list($response) = $this->setFriendProfileWithHttpInfo($friend_profile_set_request, $contentType);
        return $response;
    }

    /**
     * Operation setFriendProfileWithHttpInfo
     *
     * Set friend profile
     *

     * @param  \NexConnServerSdkPhp\Model\FriendProfileSetRequest $friend_profile_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendProfile'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\CodeOnlyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function setFriendProfileWithHttpInfo($friend_profile_set_request, string $contentType = self::contentTypes['setFriendProfile'][0])
    {
        $request = $this->setFriendProfileRequest($friend_profile_set_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation setFriendProfileAsync
     *
     * Set friend profile
     *

     * @param  \NexConnServerSdkPhp\Model\FriendProfileSetRequest $friend_profile_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setFriendProfileAsync($friend_profile_set_request, string $contentType = self::contentTypes['setFriendProfile'][0])
    {
        return $this->setFriendProfileAsyncWithHttpInfo($friend_profile_set_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation setFriendProfileAsyncWithHttpInfo
     *
     * Set friend profile
     *

     * @param  \NexConnServerSdkPhp\Model\FriendProfileSetRequest $friend_profile_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setFriendProfileAsyncWithHttpInfo($friend_profile_set_request, string $contentType = self::contentTypes['setFriendProfile'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\CodeOnlyResponse';
        $request = $this->setFriendProfileRequest($friend_profile_set_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'setFriendProfile'
     *

     * @param  \NexConnServerSdkPhp\Model\FriendProfileSetRequest $friend_profile_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setFriendProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function setFriendProfileRequest($friend_profile_set_request, string $contentType = self::contentTypes['setFriendProfile'][0])
    {

        // verify the required parameter 'friend_profile_set_request' is set
        if ($friend_profile_set_request === null || (is_array($friend_profile_set_request) && count($friend_profile_set_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $friend_profile_set_request when calling setFriendProfile'
            );
        }


        $resourcePath = '/v4/friend/profile/set';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($friend_profile_set_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($friend_profile_set_request));
            } else {
                $httpBody = $friend_profile_set_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
