<?php
/**
 * OpenChannelMetadataApi
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Do not edit the class manually.
 */

namespace NexConnServerSdkPhp\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use NexConnServerSdkPhp\ApiException;
use NexConnServerSdkPhp\Configuration;
use NexConnServerSdkPhp\FormDataProcessor;
use NexConnServerSdkPhp\HeaderSelector;
use NexConnServerSdkPhp\ObjectSerializer;

/**
 * OpenChannelMetadataApi Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */
class OpenChannelMetadataApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'batchGetOpenChannelMetadata' => [
            'application/json',
        ],
        'batchRemoveOpenChannelMetadata' => [
            'application/json',
        ],
        'batchSetOpenChannelMetadata' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation batchGetOpenChannelMetadata
     *
     * Query metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetRequest $open_channel_metadata_batch_get_request open_channel_metadata_batch_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchGetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetResponse
     */
    public function batchGetOpenChannelMetadata($open_channel_metadata_batch_get_request, string $contentType = self::contentTypes['batchGetOpenChannelMetadata'][0])
    {
        list($response) = $this->batchGetOpenChannelMetadataWithHttpInfo($open_channel_metadata_batch_get_request, $contentType);
        return $response;
    }

    /**
     * Operation batchGetOpenChannelMetadataWithHttpInfo
     *
     * Query metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetRequest $open_channel_metadata_batch_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchGetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function batchGetOpenChannelMetadataWithHttpInfo($open_channel_metadata_batch_get_request, string $contentType = self::contentTypes['batchGetOpenChannelMetadata'][0])
    {
        $request = $this->batchGetOpenChannelMetadataRequest($open_channel_metadata_batch_get_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation batchGetOpenChannelMetadataAsync
     *
     * Query metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetRequest $open_channel_metadata_batch_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchGetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchGetOpenChannelMetadataAsync($open_channel_metadata_batch_get_request, string $contentType = self::contentTypes['batchGetOpenChannelMetadata'][0])
    {
        return $this->batchGetOpenChannelMetadataAsyncWithHttpInfo($open_channel_metadata_batch_get_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation batchGetOpenChannelMetadataAsyncWithHttpInfo
     *
     * Query metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetRequest $open_channel_metadata_batch_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchGetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchGetOpenChannelMetadataAsyncWithHttpInfo($open_channel_metadata_batch_get_request, string $contentType = self::contentTypes['batchGetOpenChannelMetadata'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetResponse';
        $request = $this->batchGetOpenChannelMetadataRequest($open_channel_metadata_batch_get_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'batchGetOpenChannelMetadata'
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchGetRequest $open_channel_metadata_batch_get_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchGetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function batchGetOpenChannelMetadataRequest($open_channel_metadata_batch_get_request, string $contentType = self::contentTypes['batchGetOpenChannelMetadata'][0])
    {

        // verify the required parameter 'open_channel_metadata_batch_get_request' is set
        if ($open_channel_metadata_batch_get_request === null || (is_array($open_channel_metadata_batch_get_request) && count($open_channel_metadata_batch_get_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $open_channel_metadata_batch_get_request when calling batchGetOpenChannelMetadata'
            );
        }


        $resourcePath = '/v4/open-channel/metadata/batch/get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($open_channel_metadata_batch_get_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($open_channel_metadata_batch_get_request));
            } else {
                $httpBody = $open_channel_metadata_batch_get_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation batchRemoveOpenChannelMetadata
     *
     * Batch delete metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchRemoveRequest $open_channel_metadata_batch_remove_request open_channel_metadata_batch_remove_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemoveOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\CodeOnlyResponse
     */
    public function batchRemoveOpenChannelMetadata($open_channel_metadata_batch_remove_request, string $contentType = self::contentTypes['batchRemoveOpenChannelMetadata'][0])
    {
        list($response) = $this->batchRemoveOpenChannelMetadataWithHttpInfo($open_channel_metadata_batch_remove_request, $contentType);
        return $response;
    }

    /**
     * Operation batchRemoveOpenChannelMetadataWithHttpInfo
     *
     * Batch delete metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchRemoveRequest $open_channel_metadata_batch_remove_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemoveOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\CodeOnlyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function batchRemoveOpenChannelMetadataWithHttpInfo($open_channel_metadata_batch_remove_request, string $contentType = self::contentTypes['batchRemoveOpenChannelMetadata'][0])
    {
        $request = $this->batchRemoveOpenChannelMetadataRequest($open_channel_metadata_batch_remove_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation batchRemoveOpenChannelMetadataAsync
     *
     * Batch delete metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchRemoveRequest $open_channel_metadata_batch_remove_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemoveOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchRemoveOpenChannelMetadataAsync($open_channel_metadata_batch_remove_request, string $contentType = self::contentTypes['batchRemoveOpenChannelMetadata'][0])
    {
        return $this->batchRemoveOpenChannelMetadataAsyncWithHttpInfo($open_channel_metadata_batch_remove_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation batchRemoveOpenChannelMetadataAsyncWithHttpInfo
     *
     * Batch delete metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchRemoveRequest $open_channel_metadata_batch_remove_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemoveOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchRemoveOpenChannelMetadataAsyncWithHttpInfo($open_channel_metadata_batch_remove_request, string $contentType = self::contentTypes['batchRemoveOpenChannelMetadata'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\CodeOnlyResponse';
        $request = $this->batchRemoveOpenChannelMetadataRequest($open_channel_metadata_batch_remove_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'batchRemoveOpenChannelMetadata'
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchRemoveRequest $open_channel_metadata_batch_remove_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemoveOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function batchRemoveOpenChannelMetadataRequest($open_channel_metadata_batch_remove_request, string $contentType = self::contentTypes['batchRemoveOpenChannelMetadata'][0])
    {

        // verify the required parameter 'open_channel_metadata_batch_remove_request' is set
        if ($open_channel_metadata_batch_remove_request === null || (is_array($open_channel_metadata_batch_remove_request) && count($open_channel_metadata_batch_remove_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $open_channel_metadata_batch_remove_request when calling batchRemoveOpenChannelMetadata'
            );
        }


        $resourcePath = '/v4/open-channel/metadata/batch/remove';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($open_channel_metadata_batch_remove_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($open_channel_metadata_batch_remove_request));
            } else {
                $httpBody = $open_channel_metadata_batch_remove_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation batchSetOpenChannelMetadata
     *
     * Batch set metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchSetRequest $open_channel_metadata_batch_set_request open_channel_metadata_batch_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchSetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \NexConnServerSdkPhp\Model\CodeOnlyResponse
     */
    public function batchSetOpenChannelMetadata($open_channel_metadata_batch_set_request, string $contentType = self::contentTypes['batchSetOpenChannelMetadata'][0])
    {
        list($response) = $this->batchSetOpenChannelMetadataWithHttpInfo($open_channel_metadata_batch_set_request, $contentType);
        return $response;
    }

    /**
     * Operation batchSetOpenChannelMetadataWithHttpInfo
     *
     * Batch set metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchSetRequest $open_channel_metadata_batch_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchSetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \NexConnServerSdkPhp\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \NexConnServerSdkPhp\Model\CodeOnlyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function batchSetOpenChannelMetadataWithHttpInfo($open_channel_metadata_batch_set_request, string $contentType = self::contentTypes['batchSetOpenChannelMetadata'][0])
    {
        $request = $this->batchSetOpenChannelMetadataRequest($open_channel_metadata_batch_set_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (!$e->hasResponse() || $e->getResponse()->getStatusCode() >= 500) {
                    $this->config->markDomainFailure();
                }
                throw ApiException::fromResponse(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                $this->config->markDomainFailure();
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();
            if ($statusCode >= 500) {
                $this->config->markDomainFailure();
            }


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NexConnServerSdkPhp\Model\CodeOnlyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation batchSetOpenChannelMetadataAsync
     *
     * Batch set metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchSetRequest $open_channel_metadata_batch_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchSetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchSetOpenChannelMetadataAsync($open_channel_metadata_batch_set_request, string $contentType = self::contentTypes['batchSetOpenChannelMetadata'][0])
    {
        return $this->batchSetOpenChannelMetadataAsyncWithHttpInfo($open_channel_metadata_batch_set_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation batchSetOpenChannelMetadataAsyncWithHttpInfo
     *
     * Batch set metadata
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchSetRequest $open_channel_metadata_batch_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchSetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchSetOpenChannelMetadataAsyncWithHttpInfo($open_channel_metadata_batch_set_request, string $contentType = self::contentTypes['batchSetOpenChannelMetadata'][0])
    {
        $returnType = '\NexConnServerSdkPhp\Model\CodeOnlyResponse';
        $request = $this->batchSetOpenChannelMetadataRequest($open_channel_metadata_batch_set_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    if ($response === null || $response->getStatusCode() >= 500) {
                        $this->config->markDomainFailure();
                    }
                    $statusCode = $response ? $response->getStatusCode() : 0;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : null,
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'batchSetOpenChannelMetadata'
     *

     * @param  \NexConnServerSdkPhp\Model\OpenChannelMetadataBatchSetRequest $open_channel_metadata_batch_set_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchSetOpenChannelMetadata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function batchSetOpenChannelMetadataRequest($open_channel_metadata_batch_set_request, string $contentType = self::contentTypes['batchSetOpenChannelMetadata'][0])
    {

        // verify the required parameter 'open_channel_metadata_batch_set_request' is set
        if ($open_channel_metadata_batch_set_request === null || (is_array($open_channel_metadata_batch_set_request) && count($open_channel_metadata_batch_set_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $open_channel_metadata_batch_set_request when calling batchSetOpenChannelMetadata'
            );
        }


        $resourcePath = '/v4/open-channel/metadata/batch/set';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        
        if (isset($open_channel_metadata_batch_set_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($open_channel_metadata_batch_set_request));
            } else {
                $httpBody = $open_channel_metadata_batch_set_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('App-Key');
        if ($apiKey !== null) {
            $headers['App-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        $headers = $this->config->prepareNexconnHeaders($headers);

        $operationHost = $this->config->resolveHost($this->hostIndex);
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
