<?php
/**
 * GroupChannelMessageSendRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Do not edit the class manually.
 */

namespace NexConnServerSdkPhp\Model;

use \ArrayAccess;
use \NexConnServerSdkPhp\ObjectSerializer;

/**
 * GroupChannelMessageSendRequest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * @implements \ArrayAccess<string, mixed>
 */
class GroupChannelMessageSendRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GroupChannelMessageSendRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'from_user_id' => 'string',
        'to_channel_ids' => 'string[]',
        'to_user_ids' => 'string[]',
        'message_type' => 'string',
        'content' => 'string',
        'push_content' => 'string',
        'push_data' => 'string',
        'is_echo_to_sender' => 'int',
        'should_persist' => 'int',
        'has_mention' => 'int',
        'content_available' => 'int',
        'has_metadata' => 'bool',
        'metadata' => 'array<string,mixed>',
        'disable_push' => 'bool',
        'push_ext' => 'string',
        'disable_update_last_msg' => 'bool',
        'need_read_receipt' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'from_user_id' => null,
        'to_channel_ids' => null,
        'to_user_ids' => null,
        'message_type' => null,
        'content' => null,
        'push_content' => null,
        'push_data' => null,
        'is_echo_to_sender' => 'int32',
        'should_persist' => 'int32',
        'has_mention' => 'int32',
        'content_available' => 'int32',
        'has_metadata' => null,
        'metadata' => null,
        'disable_push' => null,
        'push_ext' => null,
        'disable_update_last_msg' => null,
        'need_read_receipt' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'from_user_id' => false,
        'to_channel_ids' => false,
        'to_user_ids' => false,
        'message_type' => false,
        'content' => false,
        'push_content' => false,
        'push_data' => false,
        'is_echo_to_sender' => false,
        'should_persist' => false,
        'has_mention' => false,
        'content_available' => false,
        'has_metadata' => false,
        'metadata' => false,
        'disable_push' => false,
        'push_ext' => false,
        'disable_update_last_msg' => false,
        'need_read_receipt' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'from_user_id' => 'fromUserId',
        'to_channel_ids' => 'toChannelIds',
        'to_user_ids' => 'toUserIds',
        'message_type' => 'messageType',
        'content' => 'content',
        'push_content' => 'pushContent',
        'push_data' => 'pushData',
        'is_echo_to_sender' => 'isEchoToSender',
        'should_persist' => 'shouldPersist',
        'has_mention' => 'hasMention',
        'content_available' => 'contentAvailable',
        'has_metadata' => 'hasMetadata',
        'metadata' => 'metadata',
        'disable_push' => 'disablePush',
        'push_ext' => 'pushExt',
        'disable_update_last_msg' => 'disableUpdateLastMsg',
        'need_read_receipt' => 'needReadReceipt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'from_user_id' => 'setFromUserId',
        'to_channel_ids' => 'setToChannelIds',
        'to_user_ids' => 'setToUserIds',
        'message_type' => 'setMessageType',
        'content' => 'setContent',
        'push_content' => 'setPushContent',
        'push_data' => 'setPushData',
        'is_echo_to_sender' => 'setIsEchoToSender',
        'should_persist' => 'setShouldPersist',
        'has_mention' => 'setHasMention',
        'content_available' => 'setContentAvailable',
        'has_metadata' => 'setHasMetadata',
        'metadata' => 'setMetadata',
        'disable_push' => 'setDisablePush',
        'push_ext' => 'setPushExt',
        'disable_update_last_msg' => 'setDisableUpdateLastMsg',
        'need_read_receipt' => 'setNeedReadReceipt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'from_user_id' => 'getFromUserId',
        'to_channel_ids' => 'getToChannelIds',
        'to_user_ids' => 'getToUserIds',
        'message_type' => 'getMessageType',
        'content' => 'getContent',
        'push_content' => 'getPushContent',
        'push_data' => 'getPushData',
        'is_echo_to_sender' => 'getIsEchoToSender',
        'should_persist' => 'getShouldPersist',
        'has_mention' => 'getHasMention',
        'content_available' => 'getContentAvailable',
        'has_metadata' => 'getHasMetadata',
        'metadata' => 'getMetadata',
        'disable_push' => 'getDisablePush',
        'push_ext' => 'getPushExt',
        'disable_update_last_msg' => 'getDisableUpdateLastMsg',
        'need_read_receipt' => 'getNeedReadReceipt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('from_user_id', $data ?? [], null);
        $this->setIfExists('to_channel_ids', $data ?? [], null);
        $this->setIfExists('to_user_ids', $data ?? [], null);
        $this->setIfExists('message_type', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('push_content', $data ?? [], null);
        $this->setIfExists('push_data', $data ?? [], null);
        $this->setIfExists('is_echo_to_sender', $data ?? [], null);
        $this->setIfExists('should_persist', $data ?? [], null);
        $this->setIfExists('has_mention', $data ?? [], null);
        $this->setIfExists('content_available', $data ?? [], null);
        $this->setIfExists('has_metadata', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('disable_push', $data ?? [], null);
        $this->setIfExists('push_ext', $data ?? [], null);
        $this->setIfExists('disable_update_last_msg', $data ?? [], null);
        $this->setIfExists('need_read_receipt', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['from_user_id'] === null) {
            $invalidProperties[] = "'from_user_id' can't be null";
        }
        if ($this->container['to_channel_ids'] === null) {
            $invalidProperties[] = "'to_channel_ids' can't be null";
        }
        if ($this->container['message_type'] === null) {
            $invalidProperties[] = "'message_type' can't be null";
        }
        if ($this->container['content'] === null) {
            $invalidProperties[] = "'content' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets from_user_id
     *
     * @return string
     */
    public function getFromUserId()
    {
        return $this->container['from_user_id'];
    }

    /**
     * Sets from_user_id
     *
     * @param string $from_user_id Sender user ID. Server-side sending does not require the sender to be a group member, but push display works best when the sender has an access token.
     *
     * @return self
     */
    public function setFromUserId($from_user_id)
    {
        if (is_null($from_user_id)) {
            throw new \InvalidArgumentException('non-nullable from_user_id cannot be null');
        }
        $this->container['from_user_id'] = $from_user_id;

        return $this;
    }

    /**
     * Gets to_channel_ids
     *
     * @return string[]
     */
    public function getToChannelIds()
    {
        return $this->container['to_channel_ids'];
    }

    /**
     * Sets to_channel_ids
     *
     * @param string[] $to_channel_ids Target group channel IDs. Up to 3 groups are supported per request. Targeted messages support only one group.
     *
     * @return self
     */
    public function setToChannelIds($to_channel_ids)
    {
        if (is_null($to_channel_ids)) {
            throw new \InvalidArgumentException('non-nullable to_channel_ids cannot be null');
        }
        $this->container['to_channel_ids'] = $to_channel_ids;

        return $this;
    }

    /**
     * Gets to_user_ids
     *
     * @return string[]|null
     */
    public function getToUserIds()
    {
        return $this->container['to_user_ids'];
    }

    /**
     * Sets to_user_ids
     *
     * @param string[]|null $to_user_ids Recipient member user IDs for a targeted group message. Only effective when sending to a single group.
     *
     * @return self
     */
    public function setToUserIds($to_user_ids)
    {
        if (is_null($to_user_ids)) {
            throw new \InvalidArgumentException('non-nullable to_user_ids cannot be null');
        }
        $this->container['to_user_ids'] = $to_user_ids;

        return $this;
    }

    /**
     * Gets message_type
     *
     * @return string
     */
    public function getMessageType()
    {
        return $this->container['message_type'];
    }

    /**
     * Sets message_type
     *
     * @param string $message_type Message type. Supports built-in types and custom types registered in the client SDK. Custom types must not start with `RC:` and must not exceed 32 characters.
     *
     * @return self
     */
    public function setMessageType($message_type)
    {
        if (is_null($message_type)) {
            throw new \InvalidArgumentException('non-nullable message_type cannot be null');
        }
        $this->container['message_type'] = $message_type;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string $content Message content payload serialized as a string. Built-in message types should use a JSON object string. Maximum size is 128 KB.
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets push_content
     *
     * @return string|null
     */
    public function getPushContent()
    {
        return $this->container['push_content'];
    }

    /**
     * Sets push_content
     *
     * @param string|null $push_content Push notification text for offline recipients. Optional for built-in user content messages and required for push-enabled custom or notification messages.
     *
     * @return self
     */
    public function setPushContent($push_content)
    {
        if (is_null($push_content)) {
            throw new \InvalidArgumentException('non-nullable push_content cannot be null');
        }
        $this->container['push_content'] = $push_content;

        return $this;
    }

    /**
     * Gets push_data
     *
     * @return string|null
     */
    public function getPushData()
    {
        return $this->container['push_data'];
    }

    /**
     * Sets push_data
     *
     * @param string|null $push_data Custom push payload data. Exposed as `appData` on mobile push payloads.
     *
     * @return self
     */
    public function setPushData($push_data)
    {
        if (is_null($push_data)) {
            throw new \InvalidArgumentException('non-nullable push_data cannot be null');
        }
        $this->container['push_data'] = $push_data;

        return $this;
    }

    /**
     * Gets is_echo_to_sender
     *
     * @return int|null
     */
    public function getIsEchoToSender()
    {
        return $this->container['is_echo_to_sender'];
    }

    /**
     * Sets is_echo_to_sender
     *
     * @param int|null $is_echo_to_sender Whether to sync the sent message to the sender's client while online. `1` enables sync and `0` disables it.
     *
     * @return self
     */
    public function setIsEchoToSender($is_echo_to_sender)
    {
        if (is_null($is_echo_to_sender)) {
            throw new \InvalidArgumentException('non-nullable is_echo_to_sender cannot be null');
        }
        $this->container['is_echo_to_sender'] = $is_echo_to_sender;

        return $this;
    }

    /**
     * Gets should_persist
     *
     * @return int|null
     */
    public function getShouldPersist()
    {
        return $this->container['should_persist'];
    }

    /**
     * Sets should_persist
     *
     * @param int|null $should_persist Whether to store the message in cloud message history. `0` means do not store and `1` means store.
     *
     * @return self
     */
    public function setShouldPersist($should_persist)
    {
        if (is_null($should_persist)) {
            throw new \InvalidArgumentException('non-nullable should_persist cannot be null');
        }
        $this->container['should_persist'] = $should_persist;

        return $this;
    }

    /**
     * Gets has_mention
     *
     * @return int|null
     */
    public function getHasMention()
    {
        return $this->container['has_mention'];
    }

    /**
     * Sets has_mention
     *
     * @param int|null $has_mention Whether this is an @mention message. Set to `1` when `content` contains `mentionedInfo`.
     *
     * @return self
     */
    public function setHasMention($has_mention)
    {
        if (is_null($has_mention)) {
            throw new \InvalidArgumentException('non-nullable has_mention cannot be null');
        }
        $this->container['has_mention'] = $has_mention;

        return $this;
    }

    /**
     * Gets content_available
     *
     * @return int|null
     */
    public function getContentAvailable()
    {
        return $this->container['content_available'];
    }

    /**
     * Sets content_available
     *
     * @param int|null $content_available iOS silent-push flag. `1` enables background delivery and `0` disables it.
     *
     * @return self
     */
    public function setContentAvailable($content_available)
    {
        if (is_null($content_available)) {
            throw new \InvalidArgumentException('non-nullable content_available cannot be null');
        }
        $this->container['content_available'] = $content_available;

        return $this;
    }

    /**
     * Gets has_metadata
     *
     * @return bool|null
     */
    public function getHasMetadata()
    {
        return $this->container['has_metadata'];
    }

    /**
     * Sets has_metadata
     *
     * @param bool|null $has_metadata Whether to enable message metadata for this message. Only effective when sending to a single group channel.
     *
     * @return self
     */
    public function setHasMetadata($has_metadata)
    {
        if (is_null($has_metadata)) {
            throw new \InvalidArgumentException('non-nullable has_metadata cannot be null');
        }
        $this->container['has_metadata'] = $has_metadata;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,mixed>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,mixed>|null $metadata Custom message metadata entries. Only effective when `hasMetadata` is `true` and the request targets a single group.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets disable_push
     *
     * @return bool|null
     */
    public function getDisablePush()
    {
        return $this->container['disable_push'];
    }

    /**
     * Sets disable_push
     *
     * @param bool|null $disable_push Whether to suppress push notifications. Only effective when the request targets a single group channel.
     *
     * @return self
     */
    public function setDisablePush($disable_push)
    {
        if (is_null($disable_push)) {
            throw new \InvalidArgumentException('non-nullable disable_push cannot be null');
        }
        $this->container['disable_push'] = $disable_push;

        return $this;
    }

    /**
     * Gets push_ext
     *
     * @return string|null
     */
    public function getPushExt()
    {
        return $this->container['push_ext'];
    }

    /**
     * Sets push_ext
     *
     * @param string|null $push_ext Extended push configuration (JSON string as accepted by `GroupChannelMsgSendInput`).
     *
     * @return self
     */
    public function setPushExt($push_ext)
    {
        if (is_null($push_ext)) {
            throw new \InvalidArgumentException('non-nullable push_ext cannot be null');
        }
        $this->container['push_ext'] = $push_ext;

        return $this;
    }

    /**
     * Gets disable_update_last_msg
     *
     * @return bool|null
     */
    public function getDisableUpdateLastMsg()
    {
        return $this->container['disable_update_last_msg'];
    }

    /**
     * Sets disable_update_last_msg
     *
     * @param bool|null $disable_update_last_msg Whether to keep this message from updating the channel's last-message preview.
     *
     * @return self
     */
    public function setDisableUpdateLastMsg($disable_update_last_msg)
    {
        if (is_null($disable_update_last_msg)) {
            throw new \InvalidArgumentException('non-nullable disable_update_last_msg cannot be null');
        }
        $this->container['disable_update_last_msg'] = $disable_update_last_msg;

        return $this;
    }

    /**
     * Gets need_read_receipt
     *
     * @return int|null
     */
    public function getNeedReadReceipt()
    {
        return $this->container['need_read_receipt'];
    }

    /**
     * Sets need_read_receipt
     *
     * @param int|null $need_read_receipt Whether to request read receipts for this persisted message. `1` requests read receipts and `0` disables them.
     *
     * @return self
     */
    public function setNeedReadReceipt($need_read_receipt)
    {
        if (is_null($need_read_receipt)) {
            throw new \InvalidArgumentException('non-nullable need_read_receipt cannot be null');
        }
        $this->container['need_read_receipt'] = $need_read_receipt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


