<?php
/**
 * GroupChannelQuitRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Do not edit the class manually.
 */

namespace NexConnServerSdkPhp\Model;

use \ArrayAccess;
use \NexConnServerSdkPhp\ObjectSerializer;

/**
 * GroupChannelQuitRequest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * @implements \ArrayAccess<string, mixed>
 */
class GroupChannelQuitRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GroupChannelQuitRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'channel_id' => 'string',
        'user_ids' => 'string[]',
        'should_delete_mute' => 'int',
        'should_delete_allowed_senders_list' => 'int',
        'should_delete_favorites' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'channel_id' => null,
        'user_ids' => null,
        'should_delete_mute' => 'int32',
        'should_delete_allowed_senders_list' => 'int32',
        'should_delete_favorites' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'channel_id' => false,
        'user_ids' => false,
        'should_delete_mute' => false,
        'should_delete_allowed_senders_list' => false,
        'should_delete_favorites' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'channel_id' => 'channelId',
        'user_ids' => 'userIds',
        'should_delete_mute' => 'shouldDeleteMute',
        'should_delete_allowed_senders_list' => 'shouldDeleteAllowedSendersList',
        'should_delete_favorites' => 'shouldDeleteFavorites'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'channel_id' => 'setChannelId',
        'user_ids' => 'setUserIds',
        'should_delete_mute' => 'setShouldDeleteMute',
        'should_delete_allowed_senders_list' => 'setShouldDeleteAllowedSendersList',
        'should_delete_favorites' => 'setShouldDeleteFavorites'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'channel_id' => 'getChannelId',
        'user_ids' => 'getUserIds',
        'should_delete_mute' => 'getShouldDeleteMute',
        'should_delete_allowed_senders_list' => 'getShouldDeleteAllowedSendersList',
        'should_delete_favorites' => 'getShouldDeleteFavorites'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('channel_id', $data ?? [], null);
        $this->setIfExists('user_ids', $data ?? [], null);
        $this->setIfExists('should_delete_mute', $data ?? [], null);
        $this->setIfExists('should_delete_allowed_senders_list', $data ?? [], null);
        $this->setIfExists('should_delete_favorites', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['channel_id'] === null) {
            $invalidProperties[] = "'channel_id' can't be null";
        }
        if ($this->container['user_ids'] === null) {
            $invalidProperties[] = "'user_ids' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets channel_id
     *
     * @return string
     */
    public function getChannelId()
    {
        return $this->container['channel_id'];
    }

    /**
     * Sets channel_id
     *
     * @param string $channel_id channel_id
     *
     * @return self
     */
    public function setChannelId($channel_id)
    {
        if (is_null($channel_id)) {
            throw new \InvalidArgumentException('non-nullable channel_id cannot be null');
        }
        $this->container['channel_id'] = $channel_id;

        return $this;
    }

    /**
     * Gets user_ids
     *
     * @return string[]
     */
    public function getUserIds()
    {
        return $this->container['user_ids'];
    }

    /**
     * Sets user_ids
     *
     * @param string[] $user_ids user_ids
     *
     * @return self
     */
    public function setUserIds($user_ids)
    {
        if (is_null($user_ids)) {
            throw new \InvalidArgumentException('non-nullable user_ids cannot be null');
        }
        $this->container['user_ids'] = $user_ids;

        return $this;
    }

    /**
     * Gets should_delete_mute
     *
     * @return int|null
     */
    public function getShouldDeleteMute()
    {
        return $this->container['should_delete_mute'];
    }

    /**
     * Sets should_delete_mute
     *
     * @param int|null $should_delete_mute `0` means keep each leaving member's mute state and `1` means remove it.
     *
     * @return self
     */
    public function setShouldDeleteMute($should_delete_mute)
    {
        if (is_null($should_delete_mute)) {
            throw new \InvalidArgumentException('non-nullable should_delete_mute cannot be null');
        }
        $this->container['should_delete_mute'] = $should_delete_mute;

        return $this;
    }

    /**
     * Gets should_delete_allowed_senders_list
     *
     * @return int|null
     */
    public function getShouldDeleteAllowedSendersList()
    {
        return $this->container['should_delete_allowed_senders_list'];
    }

    /**
     * Sets should_delete_allowed_senders_list
     *
     * @param int|null $should_delete_allowed_senders_list `0` means keep each leaving member's allowed-senders-list state and `1` means remove it.
     *
     * @return self
     */
    public function setShouldDeleteAllowedSendersList($should_delete_allowed_senders_list)
    {
        if (is_null($should_delete_allowed_senders_list)) {
            throw new \InvalidArgumentException('non-nullable should_delete_allowed_senders_list cannot be null');
        }
        $this->container['should_delete_allowed_senders_list'] = $should_delete_allowed_senders_list;

        return $this;
    }

    /**
     * Gets should_delete_favorites
     *
     * @return int|null
     */
    public function getShouldDeleteFavorites()
    {
        return $this->container['should_delete_favorites'];
    }

    /**
     * Sets should_delete_favorites
     *
     * @param int|null $should_delete_favorites `0` means keep each leaving member's favorites record and `1` means remove it.
     *
     * @return self
     */
    public function setShouldDeleteFavorites($should_delete_favorites)
    {
        if (is_null($should_delete_favorites)) {
            throw new \InvalidArgumentException('non-nullable should_delete_favorites cannot be null');
        }
        $this->container['should_delete_favorites'] = $should_delete_favorites;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


