<?php
/**
 * MessageDeleteRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Do not edit the class manually.
 */

namespace NexConnServerSdkPhp\Model;

use \ArrayAccess;
use \NexConnServerSdkPhp\ObjectSerializer;

/**
 * MessageDeleteRequest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * @implements \ArrayAccess<string, mixed>
 */
class MessageDeleteRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MessageDeleteRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'from_user_id' => 'string',
        'channel_type' => 'int',
        'channel_id' => 'string',
        'subchannel_id' => 'string',
        'message_id' => 'string',
        'sent_at' => 'int',
        'is_admin' => 'int',
        'disable_push' => 'bool',
        'extra' => 'string',
        'disable_update_last_msg' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'from_user_id' => null,
        'channel_type' => 'int32',
        'channel_id' => null,
        'subchannel_id' => null,
        'message_id' => null,
        'sent_at' => 'int64',
        'is_admin' => 'int32',
        'disable_push' => null,
        'extra' => null,
        'disable_update_last_msg' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'from_user_id' => false,
        'channel_type' => false,
        'channel_id' => false,
        'subchannel_id' => false,
        'message_id' => false,
        'sent_at' => false,
        'is_admin' => false,
        'disable_push' => false,
        'extra' => false,
        'disable_update_last_msg' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'from_user_id' => 'fromUserId',
        'channel_type' => 'channelType',
        'channel_id' => 'channelId',
        'subchannel_id' => 'subchannelId',
        'message_id' => 'messageId',
        'sent_at' => 'sentAt',
        'is_admin' => 'isAdmin',
        'disable_push' => 'disablePush',
        'extra' => 'extra',
        'disable_update_last_msg' => 'disableUpdateLastMsg'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'from_user_id' => 'setFromUserId',
        'channel_type' => 'setChannelType',
        'channel_id' => 'setChannelId',
        'subchannel_id' => 'setSubchannelId',
        'message_id' => 'setMessageId',
        'sent_at' => 'setSentAt',
        'is_admin' => 'setIsAdmin',
        'disable_push' => 'setDisablePush',
        'extra' => 'setExtra',
        'disable_update_last_msg' => 'setDisableUpdateLastMsg'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'from_user_id' => 'getFromUserId',
        'channel_type' => 'getChannelType',
        'channel_id' => 'getChannelId',
        'subchannel_id' => 'getSubchannelId',
        'message_id' => 'getMessageId',
        'sent_at' => 'getSentAt',
        'is_admin' => 'getIsAdmin',
        'disable_push' => 'getDisablePush',
        'extra' => 'getExtra',
        'disable_update_last_msg' => 'getDisableUpdateLastMsg'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('from_user_id', $data ?? [], null);
        $this->setIfExists('channel_type', $data ?? [], null);
        $this->setIfExists('channel_id', $data ?? [], null);
        $this->setIfExists('subchannel_id', $data ?? [], null);
        $this->setIfExists('message_id', $data ?? [], null);
        $this->setIfExists('sent_at', $data ?? [], null);
        $this->setIfExists('is_admin', $data ?? [], null);
        $this->setIfExists('disable_push', $data ?? [], null);
        $this->setIfExists('extra', $data ?? [], null);
        $this->setIfExists('disable_update_last_msg', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['from_user_id'] === null) {
            $invalidProperties[] = "'from_user_id' can't be null";
        }
        if ($this->container['channel_type'] === null) {
            $invalidProperties[] = "'channel_type' can't be null";
        }
        if ($this->container['channel_id'] === null) {
            $invalidProperties[] = "'channel_id' can't be null";
        }
        if ($this->container['message_id'] === null) {
            $invalidProperties[] = "'message_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets from_user_id
     *
     * @return string
     */
    public function getFromUserId()
    {
        return $this->container['from_user_id'];
    }

    /**
     * Sets from_user_id
     *
     * @param string $from_user_id Sender user ID of the original message that is being deleted.
     *
     * @return self
     */
    public function setFromUserId($from_user_id)
    {
        if (is_null($from_user_id)) {
            throw new \InvalidArgumentException('non-nullable from_user_id cannot be null');
        }
        $this->container['from_user_id'] = $from_user_id;

        return $this;
    }

    /**
     * Gets channel_type
     *
     * @return int
     */
    public function getChannelType()
    {
        return $this->container['channel_type'];
    }

    /**
     * Sets channel_type
     *
     * @param int $channel_type Channel type of the original message. Supports `1` direct, `3` group, `4` open channel, `6` system, and `10` community.
     *
     * @return self
     */
    public function setChannelType($channel_type)
    {
        if (is_null($channel_type)) {
            throw new \InvalidArgumentException('non-nullable channel_type cannot be null');
        }
        $this->container['channel_type'] = $channel_type;

        return $this;
    }

    /**
     * Gets channel_id
     *
     * @return string
     */
    public function getChannelId()
    {
        return $this->container['channel_id'];
    }

    /**
     * Sets channel_id
     *
     * @param string $channel_id Target identifier of the original message. Depending on `channelType`, this can be a user ID, group ID, open channel ID, community channel ID, or system target ID.
     *
     * @return self
     */
    public function setChannelId($channel_id)
    {
        if (is_null($channel_id)) {
            throw new \InvalidArgumentException('non-nullable channel_id cannot be null');
        }
        $this->container['channel_id'] = $channel_id;

        return $this;
    }

    /**
     * Gets subchannel_id
     *
     * @return string|null
     */
    public function getSubchannelId()
    {
        return $this->container['subchannel_id'];
    }

    /**
     * Sets subchannel_id
     *
     * @param string|null $subchannel_id Community subchannel ID. Required only when deleting a community-channel message that was sent to a specific subchannel.
     *
     * @return self
     */
    public function setSubchannelId($subchannel_id)
    {
        if (is_null($subchannel_id)) {
            throw new \InvalidArgumentException('non-nullable subchannel_id cannot be null');
        }
        $this->container['subchannel_id'] = $subchannel_id;

        return $this;
    }

    /**
     * Gets message_id
     *
     * @return string
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     *
     * @param string $message_id Unique message ID to delete. This corresponds to the message UID returned by send or routing services.
     *
     * @return self
     */
    public function setMessageId($message_id)
    {
        if (is_null($message_id)) {
            throw new \InvalidArgumentException('non-nullable message_id cannot be null');
        }
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets sent_at
     *
     * @return int|null
     */
    public function getSentAt()
    {
        return $this->container['sent_at'];
    }

    /**
     * Sets sent_at
     *
     * @param int|null $sent_at Send timestamp of the original message in milliseconds. Providing it helps the service locate the original message precisely.
     *
     * @return self
     */
    public function setSentAt($sent_at)
    {
        if (is_null($sent_at)) {
            throw new \InvalidArgumentException('non-nullable sent_at cannot be null');
        }
        $this->container['sent_at'] = $sent_at;

        return $this;
    }

    /**
     * Gets is_admin
     *
     * @return int|null
     */
    public function getIsAdmin()
    {
        return $this->container['is_admin'];
    }

    /**
     * Sets is_admin
     *
     * @param int|null $is_admin Whether the deletion is performed as an admin operation. `1` shows an admin recall indicator and `0` performs a normal sender recall.
     *
     * @return self
     */
    public function setIsAdmin($is_admin)
    {
        if (is_null($is_admin)) {
            throw new \InvalidArgumentException('non-nullable is_admin cannot be null');
        }
        $this->container['is_admin'] = $is_admin;

        return $this;
    }

    /**
     * Gets disable_push
     *
     * @return bool|null
     */
    public function getDisablePush()
    {
        return $this->container['disable_push'];
    }

    /**
     * Sets disable_push
     *
     * @param bool|null $disable_push Whether to suppress push notifications for the recall event. Not supported for open channels or community channels.
     *
     * @return self
     */
    public function setDisablePush($disable_push)
    {
        if (is_null($disable_push)) {
            throw new \InvalidArgumentException('non-nullable disable_push cannot be null');
        }
        $this->container['disable_push'] = $disable_push;

        return $this;
    }

    /**
     * Gets extra
     *
     * @return string|null
     */
    public function getExtra()
    {
        return $this->container['extra'];
    }

    /**
     * Sets extra
     *
     * @param string|null $extra Custom extension data carried with the recall operation. Not supported for community channels.
     *
     * @return self
     */
    public function setExtra($extra)
    {
        if (is_null($extra)) {
            throw new \InvalidArgumentException('non-nullable extra cannot be null');
        }
        $this->container['extra'] = $extra;

        return $this;
    }

    /**
     * Gets disable_update_last_msg
     *
     * @return bool|null
     */
    public function getDisableUpdateLastMsg()
    {
        return $this->container['disable_update_last_msg'];
    }

    /**
     * Sets disable_update_last_msg
     *
     * @param bool|null $disable_update_last_msg Whether to keep the recall operation from updating the channel's last-message preview.
     *
     * @return self
     */
    public function setDisableUpdateLastMsg($disable_update_last_msg)
    {
        if (is_null($disable_update_last_msg)) {
            throw new \InvalidArgumentException('non-nullable disable_update_last_msg cannot be null');
        }
        $this->container['disable_update_last_msg'] = $disable_update_last_msg;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


