<?php
/**
 * SystemChannelBroadcastAllRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Do not edit the class manually.
 */

namespace NexConnServerSdkPhp\Model;

use \ArrayAccess;
use \NexConnServerSdkPhp\ObjectSerializer;

/**
 * SystemChannelBroadcastAllRequest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * @implements \ArrayAccess<string, mixed>
 */
class SystemChannelBroadcastAllRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SystemChannelBroadcastAllRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'from_user_id' => 'string',
        'message_type' => 'string',
        'content' => 'string',
        'push_content' => 'string',
        'push_data' => 'string',
        'content_available' => 'int',
        'push_ext' => 'string',
        'disable_update_last_msg' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'from_user_id' => null,
        'message_type' => null,
        'content' => null,
        'push_content' => null,
        'push_data' => null,
        'content_available' => 'int32',
        'push_ext' => null,
        'disable_update_last_msg' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'from_user_id' => false,
        'message_type' => false,
        'content' => false,
        'push_content' => false,
        'push_data' => false,
        'content_available' => false,
        'push_ext' => false,
        'disable_update_last_msg' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'from_user_id' => 'fromUserId',
        'message_type' => 'messageType',
        'content' => 'content',
        'push_content' => 'pushContent',
        'push_data' => 'pushData',
        'content_available' => 'contentAvailable',
        'push_ext' => 'pushExt',
        'disable_update_last_msg' => 'disableUpdateLastMsg'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'from_user_id' => 'setFromUserId',
        'message_type' => 'setMessageType',
        'content' => 'setContent',
        'push_content' => 'setPushContent',
        'push_data' => 'setPushData',
        'content_available' => 'setContentAvailable',
        'push_ext' => 'setPushExt',
        'disable_update_last_msg' => 'setDisableUpdateLastMsg'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'from_user_id' => 'getFromUserId',
        'message_type' => 'getMessageType',
        'content' => 'getContent',
        'push_content' => 'getPushContent',
        'push_data' => 'getPushData',
        'content_available' => 'getContentAvailable',
        'push_ext' => 'getPushExt',
        'disable_update_last_msg' => 'getDisableUpdateLastMsg'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('from_user_id', $data ?? [], null);
        $this->setIfExists('message_type', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('push_content', $data ?? [], null);
        $this->setIfExists('push_data', $data ?? [], null);
        $this->setIfExists('content_available', $data ?? [], null);
        $this->setIfExists('push_ext', $data ?? [], null);
        $this->setIfExists('disable_update_last_msg', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['from_user_id'] === null) {
            $invalidProperties[] = "'from_user_id' can't be null";
        }
        if ($this->container['message_type'] === null) {
            $invalidProperties[] = "'message_type' can't be null";
        }
        if ($this->container['content'] === null) {
            $invalidProperties[] = "'content' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets from_user_id
     *
     * @return string
     */
    public function getFromUserId()
    {
        return $this->container['from_user_id'];
    }

    /**
     * Sets from_user_id
     *
     * @param string $from_user_id from_user_id
     *
     * @return self
     */
    public function setFromUserId($from_user_id)
    {
        if (is_null($from_user_id)) {
            throw new \InvalidArgumentException('non-nullable from_user_id cannot be null');
        }
        $this->container['from_user_id'] = $from_user_id;

        return $this;
    }

    /**
     * Gets message_type
     *
     * @return string
     */
    public function getMessageType()
    {
        return $this->container['message_type'];
    }

    /**
     * Sets message_type
     *
     * @param string $message_type message_type
     *
     * @return self
     */
    public function setMessageType($message_type)
    {
        if (is_null($message_type)) {
            throw new \InvalidArgumentException('non-nullable message_type cannot be null');
        }
        $this->container['message_type'] = $message_type;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets push_content
     *
     * @return string|null
     */
    public function getPushContent()
    {
        return $this->container['push_content'];
    }

    /**
     * Sets push_content
     *
     * @param string|null $push_content push_content
     *
     * @return self
     */
    public function setPushContent($push_content)
    {
        if (is_null($push_content)) {
            throw new \InvalidArgumentException('non-nullable push_content cannot be null');
        }
        $this->container['push_content'] = $push_content;

        return $this;
    }

    /**
     * Gets push_data
     *
     * @return string|null
     */
    public function getPushData()
    {
        return $this->container['push_data'];
    }

    /**
     * Sets push_data
     *
     * @param string|null $push_data push_data
     *
     * @return self
     */
    public function setPushData($push_data)
    {
        if (is_null($push_data)) {
            throw new \InvalidArgumentException('non-nullable push_data cannot be null');
        }
        $this->container['push_data'] = $push_data;

        return $this;
    }

    /**
     * Gets content_available
     *
     * @return int|null
     */
    public function getContentAvailable()
    {
        return $this->container['content_available'];
    }

    /**
     * Sets content_available
     *
     * @param int|null $content_available content_available
     *
     * @return self
     */
    public function setContentAvailable($content_available)
    {
        if (is_null($content_available)) {
            throw new \InvalidArgumentException('non-nullable content_available cannot be null');
        }
        $this->container['content_available'] = $content_available;

        return $this;
    }

    /**
     * Gets push_ext
     *
     * @return string|null
     */
    public function getPushExt()
    {
        return $this->container['push_ext'];
    }

    /**
     * Sets push_ext
     *
     * @param string|null $push_ext Extended push configuration (JSON string as accepted by `MessageBroadcastInput`).
     *
     * @return self
     */
    public function setPushExt($push_ext)
    {
        if (is_null($push_ext)) {
            throw new \InvalidArgumentException('non-nullable push_ext cannot be null');
        }
        $this->container['push_ext'] = $push_ext;

        return $this;
    }

    /**
     * Gets disable_update_last_msg
     *
     * @return bool|null
     */
    public function getDisableUpdateLastMsg()
    {
        return $this->container['disable_update_last_msg'];
    }

    /**
     * Sets disable_update_last_msg
     *
     * @param bool|null $disable_update_last_msg disable_update_last_msg
     *
     * @return self
     */
    public function setDisableUpdateLastMsg($disable_update_last_msg)
    {
        if (is_null($disable_update_last_msg)) {
            throw new \InvalidArgumentException('non-nullable disable_update_last_msg cannot be null');
        }
        $this->container['disable_update_last_msg'] = $disable_update_last_msg;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


