<?php
/**
 * CommunityChannelMessageSendRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Please update the test case below to test the model.
 */

namespace NexConnServerSdkPhp\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CommunityChannelMessageSendRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CommunityChannelMessageSendRequest
 * @package     NexConnServerSdkPhp
 * @author      OpenAPI Generator team
 * @link        https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */
class CommunityChannelMessageSendRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CommunityChannelMessageSendRequest"
     */
    public function testCommunityChannelMessageSendRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "from_user_id"
     */
    public function testPropertyFromUserId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_channel_ids"
     */
    public function testPropertyToChannelIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_user_ids"
     */
    public function testPropertyToUserIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message_type"
     */
    public function testPropertyMessageType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "push_content"
     */
    public function testPropertyPushContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "push_data"
     */
    public function testPropertyPushData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "should_persist"
     */
    public function testPropertyShouldPersist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_counted"
     */
    public function testPropertyIsCounted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "has_mention"
     */
    public function testPropertyHasMention()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content_available"
     */
    public function testPropertyContentAvailable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "push_ext"
     */
    public function testPropertyPushExt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subchannel_id"
     */
    public function testPropertySubchannelId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "has_metadata"
     */
    public function testPropertyHasMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
