<?php
/**
 * GroupChannelProfileListResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 * Generated by: https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/NexconnAI-Dev/nexconn-server-sdk-php).
 * https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Please update the test case below to test the model.
 */

namespace NexConnServerSdkPhp\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GroupChannelProfileListResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GroupChannelProfileListResponse
 * @package     NexConnServerSdkPhp
 * @author      OpenAPI Generator team
 * @link        https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */
class GroupChannelProfileListResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GroupChannelProfileListResponse"
     */
    public function testGroupChannelProfileListResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
