<?php
/**
 * GroupChannelSummaryItemTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 * Generated by: https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/NexconnAI-Dev/nexconn-server-sdk-php).
 * https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Please update the test case below to test the model.
 */

namespace NexConnServerSdkPhp\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GroupChannelSummaryItemTest Class Doc Comment
 *
 * @category    Class
 * @description GroupChannelSummaryItem
 * @package     NexConnServerSdkPhp
 * @author      OpenAPI Generator team
 * @link        https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */
class GroupChannelSummaryItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GroupChannelSummaryItem"
     */
    public function testGroupChannelSummaryItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "channel_id"
     */
    public function testPropertyChannelId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "group_profile"
     */
    public function testPropertyGroupProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
