<?php
/**
 * CommunityChannelManagementApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Please update the test case below to test the endpoint.
 */

namespace NexConnServerSdkPhp\Test\Api;

use \NexConnServerSdkPhp\Configuration;
use \NexConnServerSdkPhp\ApiException;
use \NexConnServerSdkPhp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CommunityChannelManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */
class CommunityChannelManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addCommunityChannelUserGroupUsers
     *
     * Add community channel user group users.
     *
     */
    public function testAddCommunityChannelUserGroupUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addCommunityChannelUserGroups
     *
     * Add community channel user groups.
     *
     */
    public function testAddCommunityChannelUserGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addPrivateSubchannelMembers
     *
     * Add private subchannel members.
     *
     */
    public function testAddPrivateSubchannelMembers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bindCommunityChannelUserGroup
     *
     * Bind community channel user group.
     *
     */
    public function testBindCommunityChannelUserGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkCommunityChannelMemberExist
     *
     * Check community channel member exist.
     *
     */
    public function testCheckCommunityChannelMemberExist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCommunityChannel
     *
     * Create community channel.
     *
     */
    public function testCreateCommunityChannel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCommunitySubchannel
     *
     * Create community subchannel.
     *
     */
    public function testCreateCommunitySubchannel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCommunitySubchannel
     *
     * Delete community subchannel.
     *
     */
    public function testDeleteCommunitySubchannel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dismissCommunityChannel
     *
     * Dismiss community channel.
     *
     */
    public function testDismissCommunityChannel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for joinCommunityChannel
     *
     * Join community channel.
     *
     */
    public function testJoinCommunityChannel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCommunityChannelHistoryMessages
     *
     * List community-channel history messages.
     *
     */
    public function testListCommunityChannelHistoryMessages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCommunityChannelSubchannelUserGroups
     *
     * List community channel subchannel user groups.
     *
     */
    public function testListCommunityChannelSubchannelUserGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCommunityChannelUserGroupSubchannels
     *
     * List community channel user group subchannels.
     *
     */
    public function testListCommunityChannelUserGroupSubchannels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCommunityChannelUserGroups
     *
     * List community channel user groups.
     *
     */
    public function testListCommunityChannelUserGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCommunityChannelUserUserGroups
     *
     * List community channel user user groups.
     *
     */
    public function testListCommunityChannelUserUserGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCommunitySubchannels
     *
     * List community subchannels.
     *
     */
    public function testListCommunitySubchannels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCommunityUserSubchannels
     *
     * List community user subchannels.
     *
     */
    public function testListCommunityUserSubchannels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPrivateSubchannelMembers
     *
     * List private subchannel members.
     *
     */
    public function testListPrivateSubchannelMembers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quitCommunityChannel
     *
     * Leave community channel.
     *
     */
    public function testQuitCommunityChannel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeCommunityChannelUserGroupUsers
     *
     * Remove community channel user group users.
     *
     */
    public function testRemoveCommunityChannelUserGroupUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeCommunityChannelUserGroups
     *
     * Delete community channel user groups.
     *
     */
    public function testRemoveCommunityChannelUserGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removePrivateSubchannelMembers
     *
     * Remove private subchannel members.
     *
     */
    public function testRemovePrivateSubchannelMembers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unbindCommunityChannelUserGroup
     *
     * Unbind community channel user group.
     *
     */
    public function testUnbindCommunityChannelUserGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCommunityChannelInfo
     *
     * Update community channel info.
     *
     */
    public function testUpdateCommunityChannelInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCommunitySubchannelType
     *
     * Update community subchannel type.
     *
     */
    public function testUpdateCommunitySubchannelType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
