<?php
/**
 * FriendshipApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * Contact: customercare@nexconn.ai
 * Generated by: https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/NexconnAI-Dev/nexconn-server-sdk-php).
 * https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Please update the test case below to test the endpoint.
 */

namespace NexConnServerSdkPhp\Test\Api;

use \NexConnServerSdkPhp\Configuration;
use \NexConnServerSdkPhp\ApiException;
use \NexConnServerSdkPhp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FriendshipApiTest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */
class FriendshipApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addFriend
     *
     * Add friend.
     *
     */
    public function testAddFriend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFriendPermission
     *
     * Get friend permission.
     *
     */
    public function testGetFriendPermission()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFriendRelationships
     *
     * Get friend relationships.
     *
     */
    public function testGetFriendRelationships()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFriends
     *
     * List friends.
     *
     */
    public function testListFriends()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeAllFriends
     *
     * Clean all friends.
     *
     */
    public function testRemoveAllFriends()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeFriends
     *
     * Delete friends.
     *
     */
    public function testRemoveFriends()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setFriendPermission
     *
     * Set friend permission.
     *
     */
    public function testSetFriendPermission()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setFriendProfile
     *
     * Set friend profile.
     *
     */
    public function testSetFriendProfile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
