<?php
/**
 * MessageManagementApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Please update the test case below to test the endpoint.
 */

namespace NexConnServerSdkPhp\Test\Api;

use \NexConnServerSdkPhp\Configuration;
use \NexConnServerSdkPhp\ApiException;
use \NexConnServerSdkPhp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MessageManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */
class MessageManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for broadcastOpenChannelMessage
     *
     * Broadcast to all open channels.
     *
     */
    public function testBroadcastOpenChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteChannelMessageHistory
     *
     * Delete server-side channel message history.
     *
     */
    public function testDeleteChannelMessageHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteChannelTypeMessageMetadata
     *
     * Delete message metadata.
     *
     */
    public function testDeleteChannelTypeMessageMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCommunityChannelMessageMetadata
     *
     * Delete community-channel message metadata keys.
     *
     */
    public function testDeleteCommunityChannelMessageMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMessage
     *
     * Delete a message (recall).
     *
     */
    public function testDeleteMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listChannelTypeMessageMetadata
     *
     * Get message metadata.
     *
     */
    public function testListChannelTypeMessageMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCommunityChannelMessageMetadata
     *
     * List community-channel message metadata.
     *
     */
    public function testListCommunityChannelMessageMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendCommunityChannelMessage
     *
     * Send a community channel message.
     *
     */
    public function testSendCommunityChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendDirectChannelMessage
     *
     * Send a direct message.
     *
     */
    public function testSendDirectChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendGroupChannelMessage
     *
     * Send a group message.
     *
     */
    public function testSendGroupChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendOpenChannelMessage
     *
     * Send an open channel message.
     *
     */
    public function testSendOpenChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setChannelTypeMessageMetadata
     *
     * Set message metadata.
     *
     */
    public function testSetChannelTypeMessageMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setCommunityChannelMessageMetadata
     *
     * Set community-channel message metadata.
     *
     */
    public function testSetCommunityChannelMessageMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCommunityChannelMessage
     *
     * Update community-channel message.
     *
     */
    public function testUpdateCommunityChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDirectChannelMessage
     *
     * Update direct-channel message.
     *
     */
    public function testUpdateDirectChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGroupChannelMessage
     *
     * Update group-channel message.
     *
     */
    public function testUpdateGroupChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
