<?php
/**
 * SystemMessagesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 * Please update the test case below to test the endpoint.
 */

namespace NexConnServerSdkPhp\Test\Api;

use \NexConnServerSdkPhp\Configuration;
use \NexConnServerSdkPhp\ApiException;
use \NexConnServerSdkPhp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SystemMessagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-php
 */
class SystemMessagesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for broadcastMessageOnline
     *
     * Broadcast to online users.
     *
     */
    public function testBroadcastMessageOnline()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadcastSystemChannelMessage
     *
     * Broadcast to all users (persistent).
     *
     */
    public function testBroadcastSystemChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteBroadcastMessage
     *
     * Recall broadcast to all users.
     *
     */
    public function testDeleteBroadcastMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendSystemChannelMessage
     *
     * Send a system message.
     *
     */
    public function testSendSystemChannelMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendSystemChannelPushByPackage
     *
     * Push by app package name.
     *
     */
    public function testSendSystemChannelPushByPackage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendSystemChannelPushByTag
     *
     * Push to tagged users.
     *
     */
    public function testSendSystemChannelPushByTag()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
