<?php
/**
 * UserManagementApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */

/**
 * Nexconn Server API
 *
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 * Generated by: https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/NexconnAI-Dev/nexconn-server-sdk-php).
 * https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 * Please update the test case below to test the endpoint.
 */

namespace NexConnServerSdkPhp\Test\Api;

use \NexConnServerSdkPhp\Configuration;
use \NexConnServerSdkPhp\ApiException;
use \NexConnServerSdkPhp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  NexConnServerSdkPhp
 * @author   OpenAPI Generator team
 * @link     https://github.com/NexconnAI-Dev/nexconn-server-sdk-php
 */
class UserManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for banUsers
     *
     * Ban a user.
     *
     */
    public function testBanUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for batchGetUserTags
     *
     * Get user tags.
     *
     */
    public function testBatchGetUserTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for batchSetUserTags
     *
     * Batch set user tags.
     *
     */
    public function testBatchSetUserTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for expireAccessToken
     *
     * Expire an access token.
     *
     */
    public function testExpireAccessToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUser
     *
     * Get user info.
     *
     */
    public function testGetUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserConnectionStatus
     *
     * Check user online status.
     *
     */
    public function testGetUserConnectionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for issueAccessToken
     *
     * Register a user.
     *
     */
    public function testIssueAccessToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listBannedUsers
     *
     * List banned users.
     *
     */
    public function testListBannedUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listChannelTypeMute
     *
     * List muted direct channel users.
     *
     */
    public function testListChannelTypeMute()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSoftDeletedUsers
     *
     * Query soft-deleted users.
     *
     */
    public function testListSoftDeletedUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restoreUsers
     *
     * Restore a user.
     *
     */
    public function testRestoreUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setChannelTypeMute
     *
     * Mute a user in direct channels.
     *
     */
    public function testSetChannelTypeMute()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for softDeleteUsers
     *
     * Soft-delete a user.
     *
     */
    public function testSoftDeleteUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unbanUsers
     *
     * Unban a user.
     *
     */
    public function testUnbanUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUser
     *
     * Update user info.
     *
     */
    public function testUpdateUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
